version: '3'

services:
  nginx_php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2324:80"
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - ./service.php:/var/www/html/service.php
      - ./.env:/var/www/html/.env
